In [1]:
import numpy as np

In [8]:
arr = [1, 2, 3]
matrix = [[1, 2], [3, 4]]

a = np.array(arr)
b = np.array(matrix)

print(arr, type(arr))
print(a, type(a))

print(matrix, type(matrix))
print(b, type(b))

[1, 2, 3] <class 'list'>
[1 2 3] <class 'numpy.ndarray'>
[[1, 2], [3, 4]] <class 'list'>
[[1 2]
 [3 4]] <class 'numpy.ndarray'>


In [13]:
np.arange(10, 20, 3) # start, stop, step

array([10, 13, 16, 19])

In [9]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [11]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
np.eye(4) # matrix identitas (diagonal)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [14]:
np.linspace(0, 10, 3) # start, end, totalnumber

array([ 0.,  5., 10.])

In [17]:
np.random.rand(5, 5) # random

array([[0.25189228, 0.23656491, 0.26310002, 0.37981219, 0.33317855],
       [0.09869564, 0.89314593, 0.42657834, 0.18869654, 0.98690957],
       [0.45925523, 0.33671293, 0.88167405, 0.64239376, 0.35822336],
       [0.91661897, 0.16617971, 0.00307706, 0.62555302, 0.35562628],
       [0.88920536, 0.70594365, 0.47652866, 0.81413126, 0.16911126]])

In [19]:
np.random.randint()

array([1, 5, 9, 0, 8])

In [20]:
b = np.arange(11, 20)
b = b.reshape(3, -1)
b

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [27]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
a = np.array([1, 2, 3])

print(a)
print("a's ndim {}".format(a.ndim))
print("a's shape {}".format(a.shape))
print("a's size {}".format(a.size))
print("a's dtype {}".format(a.dtype))
print("a's itemsize {}".format(a.itemsize))

[1 2 3]
a's ndim 1
a's shape (3,)
a's size 3
a's dtype int64
a's itemsize 8


In [23]:
a.max()

3

In [24]:
a.argmax()

2

In [25]:
a.min()

1

In [26]:
a.argmin()

0

In [38]:
sample

array([[20,  4, 31,  8, 37, 24],
       [28, 27, 34, 34, 11, 17],
       [20, 17,  7, 22, 37, 24],
       [31, 10, 44, 28, 38,  9],
       [49, 11, 46, 31, 43, 39],
       [36,  3, 19, 45, 28, 42]])

In [44]:
numbers = np.arange(1, 15)
numbers

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [47]:
print(numbers[2:])
print(numbers[:4])
print(numbers[0:10:2])

[ 3  4  5  6  7  8  9 10 11 12 13 14]
[1 2 3 4]
[1 3 5 7 9]


In [48]:
numbers[0:4] = 100
numbers

array([100, 100, 100, 100,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14])

In [54]:
[numbers[3], numbers[8]]

[100, 9]

In [57]:
numbers[[3, 9, 13, 10]]

array([100,  10,  14,  11])

In [63]:
c1 = numbers < 12
c1

array([False, False, False, False,  True,  True,  True,  True,  True,
        True,  True, False, False, False])

In [64]:
numbers[c1]

array([ 5,  6,  7,  8,  9, 10, 11])

In [65]:
numbers[numbers < 12]

array([ 5,  6,  7,  8,  9, 10, 11])

In [49]:
sample = np.random.randint(1, high=50, size=(6,6), dtype=int)
sample

array([[ 2,  9, 27, 22, 25, 11],
       [16,  6, 39, 34, 23, 44],
       [28, 39, 36, 40, 47, 37],
       [ 9,  9, 21, 13, 34,  1],
       [22, 15, 19, 42,  8,  3],
       [ 2, 13,  6,  8, 28,  2]])

In [51]:
sample[3:]

array([[ 9,  9, 21, 13, 34,  1],
       [22, 15, 19, 42,  8,  3],
       [ 2, 13,  6,  8, 28,  2]])

In [52]:
sample[:2,:1]

array([[ 2],
       [16]])

In [59]:
sample[[0,2,4]]

array([[ 2,  9, 27, 22, 25, 11],
       [28, 39, 36, 40, 47, 37],
       [22, 15, 19, 42,  8,  3]])