In [1]:
import numpy as np

In [3]:
arr = np.arange(1, 10)
print(arr+1)
print(4-arr)
print(arr*arr)

[ 2  3  4  5  6  7  8  9 10]
[ 3  2  1  0 -1 -2 -3 -4 -5]
[ 1  4  9 16 25 36 49 64 81]


In [4]:
arr2 = arr.reshape(3, 3)
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
arr2**2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [7]:
a = np.array([[0, 1, 2],
              [0, 2, 4],
              [0, 3, 6]])

In [8]:
np.where(a < 4, a, -1)  # -1 is broadcast

array([[ 0,  1,  2],
       [ 0,  2, -1],
       [ 0,  3, -1]])

In [9]:
base_data = (np.random.random((5, 5)) - 0.5) * 100
print("base_data = \n{}\n".format(base_data))

print("np.amin(base_data) = {}".format(np.amin(base_data)))
print("np.amax(base_data) = {}".format(np.amax(base_data)))
print("np.average(base_data) = {}".format(np.average(base_data)))
print("np.sum(base_data) = {}".format(np.sum(base_data)))
print("np.sin(base_data) = \n{}".format(np.sin(base_data)))

base_data = 
[[ -3.04222706 -32.76776332 -18.63087363 -22.93337155 -34.3768823 ]
 [-23.69651572 -37.66227296 -36.17761673  -2.47979746  33.21423425]
 [ -4.39767443 -31.35796991  22.59513422   9.19663333 -34.26624199]
 [  5.85294205 -29.73256255  29.38719732 -33.22001275 -12.43064553]
 [ 22.07504911 -24.97920288  41.86341902  42.26393828  31.02878108]]

np.amin(base_data) = -37.66227296457283
np.amax(base_data) = 42.26393827750764
np.average(base_data) = -5.786972084547415
np.sum(base_data) = -144.67430211368537
np.sin(base_data) = 
[[-0.09920216 -0.97612398  0.21694348  0.80886719 -0.17965614]
 [ 0.990959    0.03683055  0.99878494 -0.61453405  0.97423073]
 [ 0.95088478  0.05792418 -0.56792747  0.22617062 -0.28717586]
 [-0.4170919   0.99367095 -0.89696827 -0.97291111  0.13530877]
 [-0.08380213  0.1529358  -0.85352557 -0.98913239 -0.37754668]]


In [10]:
arr = np.arange(1,20)
print("Original: ", arr)
arr = arr * arr              #Multiplies each element by itself 
print("Multpiles: ",arr)
arr = arr - arr              #Subtracts each element from itself
print("Substracts: ",arr)
arr = np.arange(1,20)
arr = arr + arr              #Adds each element to itself
print("Add: ",arr)
arr = arr / arr              #Divides each element by itself
print("Divide: ",arr)
arr = np.arange(1,20)
arr = arr + 50
print("Add +50: ",arr)

Original:  [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Multpiles:  [  1   4   9  16  25  36  49  64  81 100 121 144 169 196 225 256 289 324
 361]
Substracts:  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
Add:  [ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38]
Divide:  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Add +50:  [51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69]
